# Apparently docker hub will delete my image if I don't pull it often enough. Lets solve that.
name: docker hub keep alive

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* 15 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-docker-image
        run: |
          docker pull freethenation/sentiment-api:latest
